mountaincar:
  QL:
    learning_rate: 0.2
    discount: 0.95
    episodes: 500
    epsilon: 0.9
    start_epsilon_decay: 1
    model: models/QL_agent.npy

  SARSA:
    learning_rate: 0.2
    discount: 0.95
    episodes: 500
    epsilon: 0.9
    start_epsilon_decay: 1
    model: models/SARSA_agent.npy
    
  DQN:
    batch_size: 128
    update_rate: 100
    learning_rate: 0.0001
    discount: 0.95
    episodes: 200
    epsilon: 0.9
    start_epsilon_decay: 1
    model: models/DQN_agent.pt
  
